stages:
- test

test:
  stage: test
  image: node:6.9.2
  cache:
    paths:
      - node_modules
  before_script:
    - npm install
  script:
    - npm run flow
    - npm run lint
    - npm run test-ci
